baseURL: 'https://get.j2.ms/'
languageCode: 'en-us'
title: 'get.j2.ms'

params:
  description: 'j2.ms Download Server'

menu:
  folders:
  - name: "Foundation"
    url: "foundation/"
    params:
      locked: true
